aws sns create-topic --name nodezoo_collect_part_role_info
aws sns create-topic --name nodezoo_get_info_role_info
aws sns create-topic --name nodezoo_role_info_test_true
aws sns create-topic --name nodezoo_need_part_role_info
aws sns create-topic --name nodezoo_get_package_role_source_source_npm
aws sns create-topic --name nodezoo_pull_package_role_source_source_npm
aws sns create-topic --name nodezoo_need_part_role_info
aws sns create-topic --name nodezoo_get_package_role_source_source_github
aws sns create-topic --name nodezoo_pull_package_role_source_source_github
aws sns create-topic --name nodezoo_collect_part_role_info
aws sns create-topic --name nodezoo_role_search_search_query
aws sns create-topic --name nodezoo_cmd_start_role_update
aws sns create-topic --name nodezoo_cmd_stop_role_update