aws sns create-topic --name nodezoo_process_payment_role_payment
aws sns create-topic --name nodezoo_login_with_github_role_web_scope_public
aws sns create-topic --name nodezoo_login_user_role_web_scope_public
aws sns create-topic --name nodezoo_role_web_scope_public_search_pkgs
aws sns create-topic --name nodezoo_role_web_scope_public_show_pkg
aws sns create-topic --name nodezoo_request_pass_reset_role_web_scope_public
aws sns create-topic --name nodezoo_reset_pass_role_web_scope_public
aws sns create-topic --name nodezoo_logout_user_role_web_scope_account
aws sns create-topic --name nodezoo_load_profile_role_web_scope_account
aws sns create-topic --name nodezoo_list_pkg_history_role_web_scope_account
aws sns create-topic --name nodezoo_bookmark_pkg_role_web_scope_account
aws sns create-topic --name nodezoo_list_bookmarks_role_web_scope_account
aws sns create-topic --name nodezoo_is_premium_role_web_scope_account
aws sns create-topic --name nodezoo_checkout_for_premium_role_web_scope_account_submit_checkout
aws sns create-topic --name nodezoo_need_part_role_info
aws sns create-topic --name nodezoo_collect_part_role_info
aws sns create-topic --name nodezoo_get_info_role_info
aws sns create-topic --name nodezoo_role_info_test_true
aws sns create-topic --name nodezoo_get_package_role_source_source_npm
aws sns create-topic --name nodezoo_pull_package_role_source_source_npm
aws sns create-topic --name nodezoo_get_package_role_source_source_github
aws sns create-topic --name nodezoo_pull_package_role_source_source_github
aws sns create-topic --name nodezoo_get_rate_limit_role_source_source_github
aws sns create-topic --name nodezoo_pull_npm_history_role_history
aws sns create-topic --name nodezoo_pull_github_history_role_history
aws sns create-topic --name nodezoo_list_history_role_history
aws sns create-topic --name nodezoo_role_search_search_query
aws sns create-topic --name nodezoo_fake_search_query_role_search
aws sns create-topic --name nodezoo_role_update_start_download
aws sns create-topic --name nodezoo_role_update_start_follow
aws sns create-topic --name nodezoo_role_update_start_ingest
aws sns create-topic --name nodezoo_role_update_stop_download
aws sns create-topic --name nodezoo_role_update_stop_follow
aws sns create-topic --name nodezoo_role_update_stop_ingest
aws sns create-topic --name nodezoo_process_change_role_update
aws sns create-topic --name nodezoo_role_update_stats_ingest
aws sns create-topic --name nodezoo_login_user_role_user_scope_auth
aws sns create-topic --name nodezoo_add_bookmark_role_user_scope_pkg
aws sns create-topic --name nodezoo_list_bookmarks_role_user_scope_pkg
aws sns create-topic --name nodezoo_load_bookmark_role_user_scope_pkg
aws sns create-topic --name nodezoo_is_premium_role_user
aws sns create-topic --name nodezoo_load_profile_role_user
aws sns create-topic --name nodezoo_join_premium_role_user